version: "3.9"

services:

  mock-server:
    build: ./mock-server
    container_name: mock-server
    ports:
      - "8080:8080"

  frontend:
    build: .
    container_name: realtime-frontend
    ports:
      - "3000:80"
    depends_on:
      - mock-server